In [125]:
import cv2 
import numpy as np 
import pytesseract 
import os
from pdf2image import convert_from_path
from PIL import Image
l = []
l2 = []
test = 0
dij = 0

In [12]:
f = open("data_1.json", "w")  #open json file and write it

In [19]:
detach_dir = '.'
if 'ProcessedImages' not in os.listdir(detach_dir):
    os.mkdir('ProcessedImages')
if 'Converted' not in os.listdir(detach_dir):
    os.mkdir('Converted')

In [13]:
def pick_text(img, x, y, w, h):
    crop_img = img[y:y + h, x:x + w]
    str = pytesseract.image_to_string(crop_img)
    return str

In [10]:
cv2.imshow('morpho_Image',imgo)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to tar

In [28]:
imgo = cv2.imread("/home/teena/Documents/pytessrect_API_image_text/Anmol_pdf_extraction/InvoiceReader-ML/attachments/invoice-template-in-flag-of-india-750px.png")
gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
print("gray",gray)
cv2.imshow('gray_Image', gray)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()

gray [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to target thread (0x561ef34c27e0)

QObject::moveToThread: Current thread (0x561ef34c27e0) is not the object's thread (0x561ef3660f20).
Cannot move to tar

In [144]:
linek = np.zeros((11, 11), dtype=np.uint8)
# print("linek",linek)
linek[5, ...] = 1
# print("linek",linek)
x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
cv2.imshow('morpho_Image', x)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()
print("x",x)
gray -= x
print("gray",gray)
gray = cv2.bitwise_not(gray)
ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)

NameError: name 'gray' is not defined

In [146]:
key_val = {}
def blocker(filename):
    global l
    global f
    global test
    global dij
    l = []
    x1 = 10
    y1 = 6
    imgo = cv2.imread(filename)
    gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
    linek = np.zeros((11, 11), dtype=np.uint8)
    linek[5, ...] = 1
    x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
    gray -= x
    gray = cv2.bitwise_not(gray)
    ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)
    while (True):
        rect_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (x1, y1))
        # print(rect_kernel)
        dilation = cv2.dilate(thresh1, rect_kernel, iterations=6)
        contours, hierarchy = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        test = len(contours)
        # print(test)
        if (test < 10):
            x1 -= 1
            y1 -= 1
        elif test > 30:
            x1 += 1
            y1 += 1
        else:
            break
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        l.append(pick_text(imgo, x, y, w, h))
    print("l",l)
    counter = 1  # Start the counter
    for i in l:
        key_val[f'key{counter}'] = (i.replace('\n', ' '))
        counter += 1
    print(key_val)
x = blocker("/home/teena/Documents/pytessrect_API_image_text/Anmol_pdf_extraction/InvoiceReader-ML/attachments/Document 14_4.jpg")

l ['\x0c', ' \n\n \n\nTeam One Technologies Pvt. Ltd.\nRegd. Office : 9, Satnam Mansion, 1st Floor, 190, Dr. Ambedkar Road, Near Chitra Cinema, Dadar (E), Mumbai-400 014.\nTel. : +91-22-43349999 Fax : +91-22-43349998 Email: sales@teamoneindia.com Web: www.teamoneindia.com\nCIN : U72100MH1999PTC119178\n\n \n\n \n\x0c', 'SUBJECT TO MUMBAI JURISDICTION _\n\nThis is a Computer Generated Invoice\n\n \n\x0c', ' \n\n \n\n \n\n \n\n \n\x0c', ' \n\n \n\nCompany‘s PAN : AABCT3093L\n\nDeclaration fi —\nWe declare that this invoice shows the actual price of the goods\ndescribed and that all particulars are true and correct.\n\n \n\x0c', ' \n\n \n\nAmount Chargeable (in words) _\n\nIndian Rupees Ninety Thousand Five Hundred Eighty One\nOnly\n\n \n\n \n\x0c', ' \n\n \n\n= 90,584.00\nE&OE\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n/122.00 Pcs\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\nCGST\nSGST\n\n \n\n \n\x0c', ' \n\n \n\n6,908.72\n\n \n\n \n\x0c', ' \n\n \n\n700.90"\n10,000,600\n\n \n\n \n\x0c', ' \n\n \n\n10

In [149]:
for i in key_val.values():
    print(i)


      Team One Technologies Pvt. Ltd. Regd. Office : 9, Satnam Mansion, 1st Floor, 190, Dr. Ambedkar Road, Near Chitra Cinema, Dadar (E), Mumbai-400 014. Tel. : +91-22-43349999 Fax : +91-22-43349998 Email: sales@teamoneindia.com Web: www.teamoneindia.com CIN : U72100MH1999PTC119178       
SUBJECT TO MUMBAI JURISDICTION _  This is a Computer Generated Invoice    
              
      Company‘s PAN : AABCT3093L  Declaration fi — We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.    
      Amount Chargeable (in words) _  Indian Rupees Ninety Thousand Five Hundred Eighty One Only       
      = 90,584.00 E&OE       

      /122.00 Pcs       

      CGST SGST       
      6,908.72       
      700.90" 10,000,600       
      10  11       
      8538       
      65060       
         Rate  per       
         Description of Goods       
         Amount       
         HSN/SAC     85381010  00440410  G

In [138]:
# x = ['\n\n \n\nTERMS & CONDITIONS\nPayment is due within 15 days\nState Bank of India\n\nAccount Number: 12345678\nRouting Number: 09876543210\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n12,246.00\n1,469.52\n\n313,715.52\n\n \n\n \n\x0c', ' \n\n \n\nSubtotal\nGST 12.0%\nTOTAL\n\n \n\n \n\x0c', ' \n\n \n\nAMOUNT\n9,999.00\n1,950.00\n\n297.00\n\n \n\n \n\x0c', ' \n\n \n\nUNIT PRICE\n9,999.00\n975.00\n\n99.00\n\n \n\n \n\x0c', ' \n\n \n\n2\n\n3\n\nDESCRIPTION\nFrontend design restructure\nCustom icon package\n\nGandhi mouse pad\n\n \n\n \n\x0c', ' \n\n \n\nIN-001\n29/01/2019\n\n2430/2019\n26/04/2019\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE #\nINVOICE DATE\nPO\n\nDUE DATE\n\n \n\n \n\x0c', ' \n\n \n\nSHIP TO\n\nKavindra Mannan\n264, Abdul Rehman\n‘Mumbai, Bihar 40009\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE\n\nSaffron Design\n\n77 Namrata Bldg\nDelhi, Dethi 400077\n\nBILLTO\n\nKavindra Mannan\n27, Dif City, Gupta\nDelhi, Dethi 40003\n\n \n\n \n\x0c']
# x = ['\x0c', ' \n\n \n\nTeam One Technologies Pvt. Ltd.\nRegd. Office : 9, Satnam Mansion, 1st Floor, 190, Dr. Ambedkar Road, Near Chitra Cinema, Dadar (E), Mumbai-400 014.\nTel. : +91-22-43349999 Fax : +91-22-43349998 Email: sales@teamoneindia.com Web: www.teamoneindia.com\nCIN : U72100MH1999PTC119178\n\n \n\n \n\x0c', 'SUBJECT TO MUMBAI JURISDICTION _\n\nThis is a Computer Generated Invoice\n\n \n\x0c', ' \n\n \n\n \n\n \n\n \n\x0c', ' \n\n \n\nCompany‘s PAN : AABCT3093L\n\nDeclaration fi —\nWe declare that this invoice shows the actual price of the goods\ndescribed and that all particulars are true and correct.\n\n \n\x0c', ' \n\n \n\nAmount Chargeable (in words) _\n\nIndian Rupees Ninety Thousand Five Hundred Eighty One\nOnly\n\n \n\n \n\x0c', ' \n\n \n\n= 90,584.00\nE&OE\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n/122.00 Pcs\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\nCGST\nSGST\n\n \n\n \n\x0c', ' \n\n \n\n6,908.72\n\n \n\n \n\x0c', ' \n\n \n\n700.90"\n10,000,600\n\n \n\n \n\x0c', ' \n\n \n\n10\n\n11\n\n \n\n \n\x0c', ' \n\n \n\n8538\n\n \n\n \n\x0c', ' \n\n \n\n65060\n\n \n\n \n\x0c', ' \n\n \n\n \n\nRate\n\nper\n\n \n\n \n\x0c', ' \n\n \n\n \n\nDescription of Goods\n\n \n\n \n\x0c', ' \n\n \n\n \n\nAmount\n\n \n\n \n\x0c', ' \n\n \n\n \n\nHSN/SAC\n\n \n\n85381010\n\n00440410\n\nGST Quantity\nRate _\n\n18% 1.00 Pcs\n\n1.00 Pcs\n\n18% 1.00 Pcs\n1.00 Pcs\n\n18 % 100.00 Pcs\n77.00 Pcs\n\n23.00 Pcs\n\n \n\n650.00 Pcs\n\n700.00 Pcs\n\n100.00 Pcs\n\n \n\n \n\x0c', ' \n\n \n\n¢ “SI Marks & Nos/ pt ods\nNo. Container No.\n\n9 Cantilever Tray\nBatch : ME/1561/05\nHalf Cantilever Tray\n\n10 Cable Manager for Rack1\nBatch : ME/I1561/04\n\n11 Labour Charges\n\nBatch : JN/67/01\nBatch : TO/21.11/01\nCat 6 Termination\n\n \n\n \n\x0c', ' \n\n \n\nTerms of Delivery\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\nDespatch Document No.\n\nDespatched through\n\n \n\n \n\x0c', ' \n\n \n\nDated\n\nDelivery Note Date\n| B0et-208, 31-Oct-2018, ZeJun-2018, {6-Oct-2018\nDestination\n\n \n\n \n\x0c', '\x0c', '\x0c', " \n\n \n\nbo <4\n\nTeartOne:Technologies Pvt. Ltd.\n\n190, Satnam Mansion\n\nOffice No.9, 1st Floor,\n\nDr. AB. Road, Dadar (E),\n\nMumbai - 400014\n\nGSTIN/UIN: 27AABCT3093L1ZO\n\nState Name: Maharashtra, Code : 27\nBuyer\n\nParshvanath Charitable Trust's\nA.P.Shah Institute of Technology\n\nSurvey No-12,Opp.Hypercity Mall\nKasarvadavali,GhodbundarRoad,\n\nThane (W)-400615\n\nGSTIN/UIN : 27AAATPO063G2ZS\nState Name : Maharashtra, Code : 27\n\n \n\x0c", " \n\n \n\nx Invoice(Page 3)\n\nInvoice No.\nTO18-19/GST/1736\n\nDelivery Note\n\nTOM 9GSTARD, TMG SGSTH, TOME NGSTON, TON GSTADE\nSupplier's Ref.\n\nBuyer's Order No.\n\n \n\nDated\n16-Nov-2018\nMode/Terms of Payment\n\n7 Days\nOther Reference(s)\n\nDated\n\n \n\x0c", ' \n\x0c']

data_dict = {}
current_key = ""
for i in x:
    cleaned_text = i.replace('\n\n', '\n').replace('\x0c', '').replace('','').strip()
    lines = cleaned_text.split('\n')

    for line in lines:
        if line.isupper():
            current_key = line.strip()
            data_dict[current_key] = []
        else:
            data_dict[current_key].append(line.strip())

print(data_dict)

{'TERMS & CONDITIONS': ['Payment is due within 15 days', 'State Bank of India', 'Account Number: 12345678', 'Routing Number: 09876543210', '', '12,246.00', '1,469.52', '313,715.52', 'Subtotal'], 'GST 12.0%': [], 'TOTAL': [], 'AMOUNT': ['9,999.00', '1,950.00', '297.00'], 'UNIT PRICE': ['9,999.00', '975.00', '99.00', '2', '3'], 'DESCRIPTION': ['Frontend design restructure', 'Custom icon package', 'Gandhi mouse pad'], 'IN-001': ['29/01/2019', '2430/2019', '26/04/2019'], 'INVOICE #': [], 'INVOICE DATE': [], 'PO': [], 'DUE DATE': [], 'SHIP TO': ['Kavindra Mannan', '264, Abdul Rehman', '‘Mumbai, Bihar 40009'], 'INVOICE': ['Saffron Design', '77 Namrata Bldg', 'Delhi, Dethi 400077'], 'BILLTO': ['Kavindra Mannan', '27, Dif City, Gupta', 'Delhi, Dethi 40003']}


In [132]:
for i,j in data_dict.items():
    print(i)
    print(j)

In [97]:
text = """TERMS & CONDITIONS
Payment is due within 15 days
State Bank of India
Account Number: 12345678
Routing Number: 09876543210

12,246.00 1,469.52 313,715.52
Subtotal GST 12.0% TOTAL

AMOUNT 9,999.00 1,950.00 297.00
UNIT PRICE 9,999.00 975.00 99.00

2 3 DESCRIPTION
Frontend design restructure
Custom icon package
Gandhi mouse pad

IN-001 29/01/2019 2430/2019 26/04/2019

INVOICE # INVOICE DATE PO DUE DATE

SHIP TO
Kavindra Mannan
264, Abdul Rehman
‘Mumbai, Bihar
40009

INVOICE
Saffron Design
77 Namrata Bldg
Delhi, Dethi
400077
BILLTO
Kavindra Mannan
27, Dif City, Gupta
Delhi, Dethi
40003"""

# Remove unnecessary newlines and spaces
cleaned_text = text.replace('\n\n', '\n').strip()

# Split the text into lines
lines = cleaned_text.split('\n')
print("lines",lines)
# Create the dictionary
data_dict = {}

# Iterate through the lines and extract key-value pairs
current_key = ""
for line in lines:
    if line.isupper():  # Identify keys
        current_key = line.strip()
        data_dict[current_key] = []
    else:  # Add values to the corresponding key
        data_dict[current_key].append(line.strip())

print(data_dict)


lines ['TERMS & CONDITIONS', 'Payment is due within 15 days', 'State Bank of India', 'Account Number: 12345678', 'Routing Number: 09876543210', '12,246.00 1,469.52 313,715.52', 'Subtotal GST 12.0% TOTAL', 'AMOUNT 9,999.00 1,950.00 297.00', 'UNIT PRICE 9,999.00 975.00 99.00', '2 3 DESCRIPTION', 'Frontend design restructure', 'Custom icon package', 'Gandhi mouse pad', 'IN-001 29/01/2019 2430/2019 26/04/2019', 'INVOICE # INVOICE DATE PO DUE DATE', 'SHIP TO', 'Kavindra Mannan', '264, Abdul Rehman', '‘Mumbai, Bihar', '40009', 'INVOICE', 'Saffron Design', '77 Namrata Bldg', 'Delhi, Dethi', '400077', 'BILLTO', 'Kavindra Mannan', '27, Dif City, Gupta', 'Delhi, Dethi', '40003']
{'TERMS & CONDITIONS': ['Payment is due within 15 days', 'State Bank of India', 'Account Number: 12345678', 'Routing Number: 09876543210', '12,246.00 1,469.52 313,715.52', 'Subtotal GST 12.0% TOTAL'], 'AMOUNT 9,999.00 1,950.00 297.00': [], 'UNIT PRICE 9,999.00 975.00 99.00': [], '2 3 DESCRIPTION': ['Frontend design restr

In [ ]:
# s = ''
#     for i in l:
#         s += " ".join(i)
#         s = s.replace('"', '')
#         s.replace('\n', ' ')
#         # s = " ".join(s.splitlines())
#         list_of_text.append(s)
#     print("list_of_text",list_of_text)

#     print("list_of_text[0]",list_of_text[0])

#     # s = ''
#     # s += " ".join(l)
#     # s = s.replace('"', '')
#     # # s = '{"content":"' + s
#     # s.replace('\n', ' ')
#     # s = " ".join(s.splitlines())

    
    # # f.write(s + '\n')
    # # cv2.imwrite('./ProcessedImages/final' + str(dij) + '.png', imgo)
    # # dij += 1

In [59]:
x = blocker("/home/teena/Documents/pytessrect_API_image_text/Anmol_pdf_extraction/InvoiceReader-ML/attachments/invoice-template-in-impact-black-750px.png")

list_of_text ['  \n \n   \n \n T e r m s   &   C o n d i t i o n s \n P a y m e n t   i s   d u e   w i t h i n   1 5   d a y s \n \n S t a t e   B a n k   o f   I n d i a \n A c c o u n t   N u m b e r :   1 2 3 4 5 6 7 8 \n R o u t i n g   N u m b e r :   0 9 8 7 6 5 4 3 2 1 0 \n \n   \n \n   \n \x0c', '  \n \n   \n \n T e r m s   &   C o n d i t i o n s \n P a y m e n t   i s   d u e   w i t h i n   1 5   d a y s \n \n S t a t e   B a n k   o f   I n d i a \n A c c o u n t   N u m b e r :   1 2 3 4 5 6 7 8 \n R o u t i n g   N u m b e r :   0 9 8 7 6 5 4 3 2 1 0 \n \n   \n \n   \n \x0c  \n \n   \n \n R a p   p w ) \n \n   \n \n   \n \x0c', '  \n \n   \n \n T e r m s   &   C o n d i t i o n s \n P a y m e n t   i s   d u e   w i t h i n   1 5   d a y s \n \n S t a t e   B a n k   o f   I n d i a \n A c c o u n t   N u m b e r :   1 2 3 4 5 6 7 8 \n R o u t i n g   N u m b e r :   0 9 8 7 6 5 4 3 2 1 0 \n \n   \n \n   \n \x0c  \n \n   \n \n R a p   p w ) \n \n   \n \n   \n \x0c3 1 3 ,

      Terms & Conditions Payment is due within 15 days  State Bank of India Account Number: 12345678 Routing Number: 09876543210               Rap pw)         313,715.52 a   a Total                     9,999.00 1,950.00 297.00  12,246.00 1,469.52      sie’  9,999.00 975.00 99.00  Subtotal GST 12.0%      1 Frontend design restructure 2 Custom icon package 3 Gandhi mouse pad      From        Saffron Design 77 Namrata Bldg Delhi, Delhi 400077            Ship To        Kavindra Mannan 264, Abdul Rehman Mumbai, Bihar 40009               To        Kavindra Mannan 27, Dif City, Gupta Delhi, Dethi 40003,         26104/2019   2430/2019   Tole a  29101/2019         IN-001         INVOICE 
      Terms & Conditions Payment is due within 15 days  State Bank of India Account Number: 12345678 Routing Number: 09876543210               Rap pw)         313,715.52 a   a Total                     9,999.00 1,950.00 297.00  12,246.00 1,469.52      sie’  9,999.00 975.00 99.00  Subtotal GST 12.0%      1 Front

In [80]:
def blocker(filename):
    global l
    global f
    global test
    global dij
    l = []
    x1 = 10
    y1 = 6
    imgo = cv2.imread(filename)
    gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY) #convert into greyscale image
    cv2.imshow('gray_Image', gray)
    cv2.waitKey(0)  # Wait until a key is pressed
    cv2.destroyAllWindows()
    linek = np.zeros((11, 11), dtype=np.uint8)
#     print("linek",linek)
    linek[5, ...] = 1
    x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
    cv2.imshow('morpho_Image', x)
    cv2.waitKey(0)  # Wait until a key is pressed
    cv2.destroyAllWindows()
#     print(x)
    gray -= x
    gray = cv2.bitwise_not(gray)
    ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)
    while (True):
        rect_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (x1, y1))
#         print(rect_kernel)
        dilation = cv2.dilate(thresh1, rect_kernel, iterations=6)
#         print(dilation)
        contours, hierarchy = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
#         print("contours",contours)
#         print("hierarchy",hierarchy)
        test = len(contours)
        # print(test)
        if (test < 10):
            x1 -= 1
            y1 -= 1
        elif test > 30:
            x1 += 1
            y1 += 1
        else:
            break
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
#         print(cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2))
        l.append(pick_text(imgo, x, y, w, h))
    print("l",l)

    s = ''
    s += " ".join(l)
    s = s.replace('"', '')
    s = '{"content":"' + s
    s.replace('\n', ' ')
    s += '"}'
    s = " ".join(s.splitlines())

    f.write(s + '\n')
    print(f)
    cv2.imwrite('./ProcessedImages/final' + str(dij) + '.png', imgo)
    dij += 1


In [81]:
text_image = blocker("/home/teena/Documents/pytessrect_API_image_text/Anmol_pdf_extraction/InvoiceReader-ML/attachments/invoice-template-in-flag-of-india-750px.png")

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to tar

l [' \n\n \n\nThank, yeu\n\nPayment is due within 15 days.\n\nState Bank of India\n‘Account Number: 12345678\nRouting Number: 09876543210\n\n \n\n \n\x0c', ' \n\n \n\nTERMS & CONDITIONS\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n12,246.00\n1,469.52\n\n313,715.52\n\n \n\n \n\x0c', ' \n\n \n\nSubtotal\nGST 12.0%\n\nTOTAL\n\n \n\n \n\x0c', ' \n\nAMOUNT\n9,999.00\n1,950.00\n\n297.00\n\n \n\n \n\n \n\x0c', 'UNIT PRICE\n\n \n\n \n\n9,999.00\n975.00\n99.00\n\n \n\n \n\x0c', ' \n\nDESCRIPTION\n\n \n\n \n\n1\n\n2\n\n3\n\nFrontend design restructure\nCustom icon package\n\nGandhi mouse pad\n\n \n\n \n\x0c', ' \n\n \n\nIN-001\n29/01/2019\n\n2430/2019\n26/04/2019\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE #\nINVOICE DATE\nPOE\n\nDUE DATE\n\n \n\n \n\x0c', ' \n\n \n\nSHIPTO\n\nKavindra Mannan\n264, Abdul Rehman\nMumbai, Bihar 40009\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE\n\nSaffron Design\n\n77 Namrata Bldg\nDelhi, Delhi 400077\n\nBILLTO\n\nKavindra Mannan\n27, Dif City, Gupta\nDelhi, Dethi 40003\n\n \n\n \n\x0c'