In [19]:
import cv2 
import numpy as np 
import pytesseract 
import os
from pdf2image import convert_from_path
from PIL import Image
l = []
l2 = []
test = 0
dij = 0

In [20]:
f = open("data_112.json", "w")  #open json file and write it

In [4]:
detach_dir = '.'
if 'ProcessedImages' not in os.listdir(detach_dir):
    os.mkdir('ProcessedImages')
if 'Converted' not in os.listdir(detach_dir):
    os.mkdir('Converted')

In [21]:
#use pytessrect on crop image
def pick_text(img, x, y, w, h):
    crop_img = img[y:y + h, x:x + w]
    str = pytesseract.image_to_string(crop_img)
    return str

In [6]:
# cv2.imshow('morpho_Image',imgo)
# cv2.waitKey(0)  # Wait until a key is pressed
# cv2.destroyAllWindows()

In [30]:
img = "/home/teena/Documents/OCR_IMAGE_TEXT/Converted/004_ Pentaho_Mkting_Newsletter_Q2 2017.png"

In [31]:
#sample image convert it into gray image
img = "/home/teena/Documents/OCR_IMAGE_TEXT/Converted/004_ Pentaho_Mkting_Newsletter_Q2 2017.png"
imgo = cv2.imread("/home/teena/Documents/OCR_IMAGE_TEXT/Converted/004_ Pentaho_Mkting_Newsletter_Q2 2017.png")
gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
print("gray",gray)
cv2.imshow('gray_Image', gray)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()

gray [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to tar

In [32]:
#after morphology operation
linek = np.zeros((11, 11), dtype=np.uint8)
# print("linek",linek)
linek[5, ...] = 1
# print("linek",linek)
x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=5)
cv2.imshow('morpho_Image', x)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()
print("x",x)
gray -= x
print("gray",gray)
gray = cv2.bitwise_not(gray)
ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to target thread (0x561a378aa770)

QObject::moveToThread: Current thread (0x561a378aa770) is not the object's thread (0x561a378e6d70).
Cannot move to tar

x [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
gray [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [40]:
# imgo = cv2.imread("/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image/final_cropped1.png")
# gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
# print("gray",gray)
# cv2.imshow('gray_Image', gray)
# cv2.waitKey(0)  # Wait until a key is pressed
# cv2.destroyAllWindows()

[ WARN:0@9585.021] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image/final_cropped1.png'): can't open/read file: check file path/integrity


error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [33]:
key_val = {}
dij = 0
def blocker(filename):
    global l
    global f
    global test
    global dij
    l = []
    x1 = 20
    y1 = 10
    imgo = cv2.imread(filename)
    gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
    linek = np.zeros((11, 11), dtype=np.uint8)
    linek[5, ...] = 1
    x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
    gray -= x
    gray = cv2.bitwise_not(gray)
    # print("gray",gray)
    ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)
    while (True):
        rect_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (x1, y1))
        # print(rect_kernel)
        dilation = cv2.dilate(thresh1, rect_kernel, iterations=6)
        contours, hierarchy = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # print("contours",contours)
        # print("hierarchy",hierarchy)
        test = len(contours)
        print("test",test)
        # print(test)
        if (test < 10):
            x1 -= 1
            y1 -= 1
        elif test > 30:
            x1 += 1
            y1 += 1
        else:
            break
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        print("x",x)
        print("y",y)
        print("w",w)
        print("h",h)
        cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        # z = cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        roi = imgo[y:y+h, x:x+w]
        # v = cv2.imread(z)
        cv2.imwrite('./cropped_image/final_cropped' +str(dij)+ '.png',roi)
        dij += 1
x = blocker(img)

test 27
x 26
y 2060
w 115
h 60
x 1105
y 2023
w 305
h 79
x 150
y 1785
w 1736
h 222
x 26
y 1772
w 115
h 57
x 359
y 1613
w 797
h 83
x 1487
y 1538
w 854
h 187
x 26
y 1484
w 115
h 57
x 2033
y 1397
w 235
h 79
x 2033
y 1246
w 235
h 129
x 1270
y 1244
w 705
h 230
x 2033
y 1006
w 235
h 79
x 1973
y 919
w 360
h 79
x 1761
y 919
w 163
h 79
x 1456
y 919
w 274
h 79
x 1247
y 919
w 166
h 79
x 26
y 919
w 1121
h 317
x 555
y 917
w 319
h 79
x 26
y 855
w 115
h 57
x 2061
y 819
w 177
h 79
x 1464
y 817
w 429
h 79
x 516
y 721
w 482
h 126
x 1424
y 617
w 966
h 181
x 643
y 617
w 231
h 79
x 873
y 358
w 1382
h 237
x 84
y 267
w 584
h 193
x 1348
y 254
w 442
h 93
x 26
y 200
w 115
h 60


In [18]:
imgo = cv2.imread(img)
gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
linek = np.zeros((11, 11), dtype=np.uint8)
linek[5, ...] = 1
x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
gray -= x
gray = cv2.bitwise_not(gray)
print(gray)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [19]:
ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)

In [21]:
print(ret)
print(thresh1)

146.0
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
key_val = {}
dij = 0
def blocker(filename):
    global l
    global f
    global test
    global dij
    l = []
    x1 = 18
    y1 = 7
    imgo = cv2.imread(filename)
    gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
    linek = np.zeros((11, 11), dtype=np.uint8)
    linek[5, ...] = 1
    x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
    gray -= x
    gray = cv2.bitwise_not(gray)
    # print("gray",gray)
    ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)
    while (True):
        rect_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (x1, y1))
        # print(rect_kernel)
        dilation = cv2.dilate(thresh1, rect_kernel, iterations=6)
        contours, hierarchy = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # print("contours",contours)
        # print("hierarchy",hierarchy)
        test = len(contours)
        print("test",test)
        # print(test)
        if (test < 10):
            x1 -= 1
            y1 -= 1
        elif test > 30:
            x1 += 1
            y1 += 1
        else:
            break
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        print("x",x)
        print("y",y)
        print("w",w)
        print("h",h)
        cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        # z = cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        roi = imgo[y:y+h, x:x+w]
        # v = cv2.imread(z)
        cv2.imwrite('./cropped_image/final_cropped' +str(dij)+ '.png',roi)
        dij += 1
x = blocker(img)

In [18]:
from tabula import read_pdf
from tabulate import tabulate

x = "/home/teena/Documents/OCR_IMAGE_TEXT/attachments/004_ Pentaho_Mkting_Newsletter_Q2 2017.pdf"
#reads table from pdf file
df = read_pdf(x,pages="all") #address of pdf file
print(tabulate(df))


JavaNotFoundError: `java` command is not found from this Python process.Please ensure Java is installed and PATH is set for `java`

In [12]:
l = []
image_path = "/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image/final_cropped8.png"
image = cv2.imread(image_path)
st = pytesseract.image_to_string(image)
# print(st)
l.append(st)

In [13]:
l

[' \n\n \n\nBill To\n\nKavindra Mannan\n27, Dif City, Gupta\nDelhi, Dethi 40003\n\n \n\n \n\x0c']

In [34]:
import os
import cv2
l = []

# Specify the directory path containing the images
directory_path = '/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image'

# Get the list of files in the directory
file_list = os.listdir(directory_path)

# Loop through each file in the directory
for file_name in file_list:
    # Construct the full path of the image file
    image_path = os.path.join(directory_path, file_name)

    # Read the image using OpenCV
    image = cv2.imread(image_path)
    st = pytesseract.image_to_string(image)
    cleaned_text = st.strip().replace('\n', ' ').replace('\x0c', '')
    print("cleaned_text",cleaned_text)
    l.append([cleaned_text])
print(l)

cleaned_text 
cleaned_text AMOUNT (USD) |
cleaned_text BILL TO:
cleaned_text $500.00
cleaned_text DESCRIPTION
cleaned_text $500.00
cleaned_text UNIT PRICE
cleaned_text 
cleaned_text 
cleaned_text QTY
cleaned_text ‘ASHNIK  DELIVERING SOLUTIONS, THE OPEN SOURCE WAY.
cleaned_text DATE
cleaned_text 
cleaned_text 101 Cecil Street, #11-11 Tong Eng Building, Singapore 069533 | Phone: (65) 6438 3504 Email: success@ashnik.com | www.ashnik.com GST No.: 200915920G  INVOICE
cleaned_text $500.00 $0.00
cleaned_text In words : US Dollars Five Hundred only
cleaned_text No.  1.)     DESCRIPTION  Newsletter Article Promotion - Q2 2017 (April to June)
cleaned_text SUBTOTAL] _ TAX @  TRANSPORT & HANDLING]
cleaned_text Payment - Immediate  Kindly make all cheques payable to Ashnik Pte Ltd.     For Bank transfer: Bank — OCBC, Singapore | Account number : 503042327301 Bank code : 7339 Swift code : OCBCSGSG If you have any questions concerning this invoice, please contact us (65) 6438 3504 or email us at succ

In [49]:
for i in l:
    print(i[0])

Ship To  Kavindra Mannan 264, Abdul Rehman Mumbai, Bihar 40009  Invoice # IN-001 Invoice Date 29/01/2019 P.O.# 2430/2019  Due Date 26/04/2019
Payment is due within 1 days  State Bank of India Account Number: 12345678 Routing Number: 09876543210
Subtotal 12,246.00  GST 12.0% 1,469.52  INVOICE TOTAL 13,715.52
Bill To  Kavindra Mannan 27, Dif City, Gupta Delhi, Dethi 40003
AMOUNT     9,999.00 1,950.00 297.00
Saffron Design  77 Namrata Bldg Delhi, Dethi 400077

Terms & Conditions
UNIT PRICE     9,999.00 975.00 99.00
QTy     DESCRIPTION  Frontend design restructure Custom icon package  Gandhi mouse pad


In [15]:
import json
formatted_data = []
m = 0
for sublist in l:
    formatted_data.append({'line'+str(m): sublist[0].strip()})
    m+=1

In [16]:
file_path = 'data_112.json'

with open(file_path, 'w') as file:
    json.dump(formatted_data, file, indent=4)

In [24]:
for i in l:
    for j in i:
        bill_to_lines = j.strip().split('\n')
        bill_to_info = bill_to_lines[2:]
        for line in bill_to_lines:
            print(line.strip())

Bill To  Kavindra Mannan 27, Dif City, Gupta Delhi, Deini 40003,  Ship To  Kavindra Mannan 264, Abdul Rehman Mumbai, Bihar 40009  Invoice # 1N-001 Invoice Date. 29/01/2019 PO 2430/2019  Due Date 26/04/2019
Terms & Conditions Payment is due within 15 days State Bank of India  Account Number: 12345678 Routing Number: 09876543210
313,715.52
Saffron Design  77 Namrata Bldg Delhi, Delhi 400077
Subtotal 12,246.00 GST 12.0% 1,469.52

Total

aa rag  9,999.00 9,999.00 975.00 1,950.00 99.00 297.00
uy  D     eC  Frontend design restructure ‘Custom icon package Gandhi mouse pad


In [ ]:
#  l.append([pick_text(imgo, x, y, w, h)])
#     print("l",l)
#     counter = 1  # Start the counter
#     for i in l:
#         key_val[f'key{counter}'] = (i.replace('\n', ' '))
#         counter += 1
#     print(key_val)
# x = blocker("/home/teena/Documents/OCR_IMAGE_TEXT/attachments/invoice-template-in-mono-red-750px.png")

In [16]:
str = pytesseract.image_to_string("/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image/final_cropped0.png")

In [19]:
str

' \n\n \n\nTERMS & CONDITIONS\nPayment is due within 15 days\nState Bank of india\n\nAccount Number: 12345678\nRouting Number: 09876543210\n\n \n\n \n\x0c'

In [11]:
import cv2

# Read the image
image = cv2.imread('/home/teena/Documents/OCR_IMAGE_TEXT/attachments/invoice-template-in-lotus-purple-750px.png')

# Define the coordinates of the rectangle
x, y, w, h = 100, 100, 200, 150  # Example values; adjust according to your requirements

# Draw the rectangle on the image
cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)

# Extract the region of interest (ROI) using array slicing
roi = image[y:y+h, x:x+w]

# Save the ROI as a separate image
cv2.imwrite('roi_image.jpg', roi)

# Display a message upon successful save
print("ROI image saved successfully!")


ROI image saved successfully!


In [138]:
# x = ['\n\n \n\nTERMS & CONDITIONS\nPayment is due within 15 days\nState Bank of India\n\nAccount Number: 12345678\nRouting Number: 09876543210\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n12,246.00\n1,469.52\n\n313,715.52\n\n \n\n \n\x0c', ' \n\n \n\nSubtotal\nGST 12.0%\nTOTAL\n\n \n\n \n\x0c', ' \n\n \n\nAMOUNT\n9,999.00\n1,950.00\n\n297.00\n\n \n\n \n\x0c', ' \n\n \n\nUNIT PRICE\n9,999.00\n975.00\n\n99.00\n\n \n\n \n\x0c', ' \n\n \n\n2\n\n3\n\nDESCRIPTION\nFrontend design restructure\nCustom icon package\n\nGandhi mouse pad\n\n \n\n \n\x0c', ' \n\n \n\nIN-001\n29/01/2019\n\n2430/2019\n26/04/2019\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE #\nINVOICE DATE\nPO\n\nDUE DATE\n\n \n\n \n\x0c', ' \n\n \n\nSHIP TO\n\nKavindra Mannan\n264, Abdul Rehman\n‘Mumbai, Bihar 40009\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE\n\nSaffron Design\n\n77 Namrata Bldg\nDelhi, Dethi 400077\n\nBILLTO\n\nKavindra Mannan\n27, Dif City, Gupta\nDelhi, Dethi 40003\n\n \n\n \n\x0c']
# x = ['\x0c', ' \n\n \n\nTeam One Technologies Pvt. Ltd.\nRegd. Office : 9, Satnam Mansion, 1st Floor, 190, Dr. Ambedkar Road, Near Chitra Cinema, Dadar (E), Mumbai-400 014.\nTel. : +91-22-43349999 Fax : +91-22-43349998 Email: sales@teamoneindia.com Web: www.teamoneindia.com\nCIN : U72100MH1999PTC119178\n\n \n\n \n\x0c', 'SUBJECT TO MUMBAI JURISDICTION _\n\nThis is a Computer Generated Invoice\n\n \n\x0c', ' \n\n \n\n \n\n \n\n \n\x0c', ' \n\n \n\nCompany‘s PAN : AABCT3093L\n\nDeclaration fi —\nWe declare that this invoice shows the actual price of the goods\ndescribed and that all particulars are true and correct.\n\n \n\x0c', ' \n\n \n\nAmount Chargeable (in words) _\n\nIndian Rupees Ninety Thousand Five Hundred Eighty One\nOnly\n\n \n\n \n\x0c', ' \n\n \n\n= 90,584.00\nE&OE\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n/122.00 Pcs\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\nCGST\nSGST\n\n \n\n \n\x0c', ' \n\n \n\n6,908.72\n\n \n\n \n\x0c', ' \n\n \n\n700.90"\n10,000,600\n\n \n\n \n\x0c', ' \n\n \n\n10\n\n11\n\n \n\n \n\x0c', ' \n\n \n\n8538\n\n \n\n \n\x0c', ' \n\n \n\n65060\n\n \n\n \n\x0c', ' \n\n \n\n \n\nRate\n\nper\n\n \n\n \n\x0c', ' \n\n \n\n \n\nDescription of Goods\n\n \n\n \n\x0c', ' \n\n \n\n \n\nAmount\n\n \n\n \n\x0c', ' \n\n \n\n \n\nHSN/SAC\n\n \n\n85381010\n\n00440410\n\nGST Quantity\nRate _\n\n18% 1.00 Pcs\n\n1.00 Pcs\n\n18% 1.00 Pcs\n1.00 Pcs\n\n18 % 100.00 Pcs\n77.00 Pcs\n\n23.00 Pcs\n\n \n\n650.00 Pcs\n\n700.00 Pcs\n\n100.00 Pcs\n\n \n\n \n\x0c', ' \n\n \n\n¢ “SI Marks & Nos/ pt ods\nNo. Container No.\n\n9 Cantilever Tray\nBatch : ME/1561/05\nHalf Cantilever Tray\n\n10 Cable Manager for Rack1\nBatch : ME/I1561/04\n\n11 Labour Charges\n\nBatch : JN/67/01\nBatch : TO/21.11/01\nCat 6 Termination\n\n \n\n \n\x0c', ' \n\n \n\nTerms of Delivery\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\nDespatch Document No.\n\nDespatched through\n\n \n\n \n\x0c', ' \n\n \n\nDated\n\nDelivery Note Date\n| B0et-208, 31-Oct-2018, ZeJun-2018, {6-Oct-2018\nDestination\n\n \n\n \n\x0c', '\x0c', '\x0c', " \n\n \n\nbo <4\n\nTeartOne:Technologies Pvt. Ltd.\n\n190, Satnam Mansion\n\nOffice No.9, 1st Floor,\n\nDr. AB. Road, Dadar (E),\n\nMumbai - 400014\n\nGSTIN/UIN: 27AABCT3093L1ZO\n\nState Name: Maharashtra, Code : 27\nBuyer\n\nParshvanath Charitable Trust's\nA.P.Shah Institute of Technology\n\nSurvey No-12,Opp.Hypercity Mall\nKasarvadavali,GhodbundarRoad,\n\nThane (W)-400615\n\nGSTIN/UIN : 27AAATPO063G2ZS\nState Name : Maharashtra, Code : 27\n\n \n\x0c", " \n\n \n\nx Invoice(Page 3)\n\nInvoice No.\nTO18-19/GST/1736\n\nDelivery Note\n\nTOM 9GSTARD, TMG SGSTH, TOME NGSTON, TON GSTADE\nSupplier's Ref.\n\nBuyer's Order No.\n\n \n\nDated\n16-Nov-2018\nMode/Terms of Payment\n\n7 Days\nOther Reference(s)\n\nDated\n\n \n\x0c", ' \n\x0c']

data_dict = {}
current_key = ""
for i in x:
    cleaned_text = i.replace('\n\n', '\n').replace('\x0c', '').replace('','').strip()
    lines = cleaned_text.split('\n')

    for line in lines:
        if line.isupper():
            current_key = line.strip()
            data_dict[current_key] = []
        else:
            data_dict[current_key].append(line.strip())

print(data_dict)

{'TERMS & CONDITIONS': ['Payment is due within 15 days', 'State Bank of India', 'Account Number: 12345678', 'Routing Number: 09876543210', '', '12,246.00', '1,469.52', '313,715.52', 'Subtotal'], 'GST 12.0%': [], 'TOTAL': [], 'AMOUNT': ['9,999.00', '1,950.00', '297.00'], 'UNIT PRICE': ['9,999.00', '975.00', '99.00', '2', '3'], 'DESCRIPTION': ['Frontend design restructure', 'Custom icon package', 'Gandhi mouse pad'], 'IN-001': ['29/01/2019', '2430/2019', '26/04/2019'], 'INVOICE #': [], 'INVOICE DATE': [], 'PO': [], 'DUE DATE': [], 'SHIP TO': ['Kavindra Mannan', '264, Abdul Rehman', '‘Mumbai, Bihar 40009'], 'INVOICE': ['Saffron Design', '77 Namrata Bldg', 'Delhi, Dethi 400077'], 'BILLTO': ['Kavindra Mannan', '27, Dif City, Gupta', 'Delhi, Dethi 40003']}


In [132]:
for i,j in data_dict.items():
    print(i)
    print(j)

In [97]:
text = """TERMS & CONDITIONS
Payment is due within 15 days
State Bank of India
Account Number: 12345678
Routing Number: 09876543210

12,246.00 1,469.52 313,715.52
Subtotal GST 12.0% TOTAL

AMOUNT 9,999.00 1,950.00 297.00
UNIT PRICE 9,999.00 975.00 99.00

2 3 DESCRIPTION
Frontend design restructure
Custom icon package
Gandhi mouse pad

IN-001 29/01/2019 2430/2019 26/04/2019

INVOICE # INVOICE DATE PO DUE DATE

SHIP TO
Kavindra Mannan
264, Abdul Rehman
‘Mumbai, Bihar
40009

INVOICE
Saffron Design
77 Namrata Bldg
Delhi, Dethi
400077
BILLTO
Kavindra Mannan
27, Dif City, Gupta
Delhi, Dethi
40003"""

# Remove unnecessary newlines and spaces
cleaned_text = text.replace('\n\n', '\n').strip()

# Split the text into lines
lines = cleaned_text.split('\n')
print("lines",lines)
# Create the dictionary
data_dict = {}

# Iterate through the lines and extract key-value pairs
current_key = ""
for line in lines:
    if line.isupper():  # Identify keys
        current_key = line.strip()
        data_dict[current_key] = []
    else:  # Add values to the corresponding key
        data_dict[current_key].append(line.strip())

print(data_dict)


lines ['TERMS & CONDITIONS', 'Payment is due within 15 days', 'State Bank of India', 'Account Number: 12345678', 'Routing Number: 09876543210', '12,246.00 1,469.52 313,715.52', 'Subtotal GST 12.0% TOTAL', 'AMOUNT 9,999.00 1,950.00 297.00', 'UNIT PRICE 9,999.00 975.00 99.00', '2 3 DESCRIPTION', 'Frontend design restructure', 'Custom icon package', 'Gandhi mouse pad', 'IN-001 29/01/2019 2430/2019 26/04/2019', 'INVOICE # INVOICE DATE PO DUE DATE', 'SHIP TO', 'Kavindra Mannan', '264, Abdul Rehman', '‘Mumbai, Bihar', '40009', 'INVOICE', 'Saffron Design', '77 Namrata Bldg', 'Delhi, Dethi', '400077', 'BILLTO', 'Kavindra Mannan', '27, Dif City, Gupta', 'Delhi, Dethi', '40003']
{'TERMS & CONDITIONS': ['Payment is due within 15 days', 'State Bank of India', 'Account Number: 12345678', 'Routing Number: 09876543210', '12,246.00 1,469.52 313,715.52', 'Subtotal GST 12.0% TOTAL'], 'AMOUNT 9,999.00 1,950.00 297.00': [], 'UNIT PRICE 9,999.00 975.00 99.00': [], '2 3 DESCRIPTION': ['Frontend design restr

In [ ]:
# s = ''
#     for i in l:
#         s += " ".join(i)
#         s = s.replace('"', '')
#         s.replace('\n', ' ')
#         # s = " ".join(s.splitlines())
#         list_of_text.append(s)
#     print("list_of_text",list_of_text)

#     print("list_of_text[0]",list_of_text[0])

#     # s = ''
#     # s += " ".join(l)
#     # s = s.replace('"', '')
#     # # s = '{"content":"' + s
#     # s.replace('\n', ' ')
#     # s = " ".join(s.splitlines())

    
    # # f.write(s + '\n')
    # # cv2.imwrite('./ProcessedImages/final' + str(dij) + '.png', imgo)
    # # dij += 1

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to target thread (0x558fdd4d9b80)

QObject::moveToThread: Current thread (0x558fdd4d9b80) is not the object's thread (0x558fdd3f69a0).
Cannot move to tar

l [' \n\n \n\nThank, yeu\n\nPayment is due within 15 days.\n\nState Bank of India\n‘Account Number: 12345678\nRouting Number: 09876543210\n\n \n\n \n\x0c', ' \n\n \n\nTERMS & CONDITIONS\n\n \n\n \n\x0c', '\x0c', ' \n\n \n\n12,246.00\n1,469.52\n\n313,715.52\n\n \n\n \n\x0c', ' \n\n \n\nSubtotal\nGST 12.0%\n\nTOTAL\n\n \n\n \n\x0c', ' \n\nAMOUNT\n9,999.00\n1,950.00\n\n297.00\n\n \n\n \n\n \n\x0c', 'UNIT PRICE\n\n \n\n \n\n9,999.00\n975.00\n99.00\n\n \n\n \n\x0c', ' \n\nDESCRIPTION\n\n \n\n \n\n1\n\n2\n\n3\n\nFrontend design restructure\nCustom icon package\n\nGandhi mouse pad\n\n \n\n \n\x0c', ' \n\n \n\nIN-001\n29/01/2019\n\n2430/2019\n26/04/2019\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE #\nINVOICE DATE\nPOE\n\nDUE DATE\n\n \n\n \n\x0c', ' \n\n \n\nSHIPTO\n\nKavindra Mannan\n264, Abdul Rehman\nMumbai, Bihar 40009\n\n \n\n \n\x0c', ' \n\n \n\nINVOICE\n\nSaffron Design\n\n77 Namrata Bldg\nDelhi, Delhi 400077\n\nBILLTO\n\nKavindra Mannan\n27, Dif City, Gupta\nDelhi, Dethi 40003\n\n \n\n \n\x0c'