In [12]:
import cv2 
import numpy as np 
import pytesseract 
import os
from pdf2image import convert_from_path
from PIL import Image
l = []
l2 = []
test = 0
dij = 0

In [13]:
f = open("data_rough.json", "w")  #open json file and write it

In [4]:
detach_dir = '.'
if 'ProcessedImages' not in os.listdir(detach_dir):
    os.mkdir('ProcessedImages')
if 'Converted' not in os.listdir(detach_dir):
    os.mkdir('Converted')

In [38]:
#use pytessrect on crop image
def pick_text(img, x, y, w, h):
    crop_img = img[y:y + h, x:x + w]
    str = pytesseract.image_to_string(crop_img)
    return str

In [6]:
# cv2.imshow('morpho_Image',imgo)
# cv2.waitKey(0)  # Wait until a key is pressed
# cv2.destroyAllWindows()

In [14]:
img = "/home/teena/Documents/OCR_IMAGE_TEXT/ProcessedImages/final21.png"

In [15]:
#sample image convert it into gray image
img = "/home/teena/Documents/OCR_IMAGE_TEXT/ProcessedImages/final21.png"
imgo = cv2.imread("/home/teena/Documents/OCR_IMAGE_TEXT/ProcessedImages/final21.png")
gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
print("gray",gray)
cv2.imshow('gray_Image', gray)
cv2.waitKey(0)  # Wait until a key is pressed
cv2.destroyAllWindows()

gray [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to target thread (0x562ece744e60)

QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to target thread (0x562ece744e60)

QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to target thread (0x562ece744e60)

QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to target thread (0x562ece744e60)

QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to target thread (0x562ece744e60)

QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to target thread (0x562ece744e60)

QObject::moveToThread: Current thread (0x562ece744e60) is not the object's thread (0x562ece8f45c0).
Cannot move to tar

In [40]:
# imgo = cv2.imread("/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image/final_cropped1.png")
# gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
# print("gray",gray)
# cv2.imshow('gray_Image', gray)
# cv2.waitKey(0)  # Wait until a key is pressed
# cv2.destroyAllWindows()

[ WARN:0@9585.021] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image/final_cropped1.png'): can't open/read file: check file path/integrity


error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [16]:
key_val = {}
dij = 0
def blocker(filename):
    global l
    global f
    global test
    global dij
    l = []
    x1 = 7
    y1 = 7
    imgo = cv2.imread(filename)
    gray = cv2.cvtColor(imgo, cv2.COLOR_BGR2GRAY)
    linek = np.zeros((11, 11), dtype=np.uint8)
    linek[5, ...] = 1
    x = cv2.morphologyEx(gray, cv2.MORPH_OPEN, linek, iterations=1)
    gray -= x
    gray = cv2.bitwise_not(gray)
    # print("gray",gray)
    ret, thresh1 = cv2.threshold(gray, 0, 255, cv2.THRESH_OTSU | cv2.THRESH_BINARY_INV)
    while (True):
        rect_kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (x1, y1))
        # print(rect_kernel)
        dilation = cv2.dilate(thresh1, rect_kernel, iterations=6)
        contours, hierarchy = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        # print("contours",contours)
        # print("hierarchy",hierarchy)
        test = len(contours)
        print("test",test)
        print(test)
        if (test < 10):
            x1 -= 1
            y1 -= 1
        elif test > 30:
            x1 += 1
            y1 += 1
        else:
            break
    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        print("x",x)
        print("y",y)
        print("w",w)
        print("h",h)
        cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        # z = cv2.rectangle(imgo, (x, y), (x + w, y + h), (0, 255, 0), 2)
        roi = imgo[y:y+h, x:x+w]
        # v = cv2.imread(z)
        cv2.imwrite('./cropped_image/final_cropped' +str(dij)+ '.png',roi)
        dij += 1
x = blocker(img)

test 18
18
x 38
y 871
w 223
h 155
x 731
y 787
w 19
h 37
x 537
y 711
w 187
h 93
x 731
y 692
w 19
h 37
x 38
y 630
w 136
h 55
x 471
y 552
w 242
h 134
x 50
y 464
w 39
h 77
x 610
y 392
w 103
h 150
x 444
y 392
w 137
h 150
x 123
y 392
w 187
h 150
x 52
y 392
w 63
h 48
x 284
y 272
w 152
h 115
x 39
y 272
w 134
h 115
x 617
y 161
w 95
h 123
x 432
y 158
w 154
h 126
x 38
y 158
w 142
h 111
x 602
y 65
w 100
h 56
x 38
y 33
w 268
h 100


In [17]:
import os
import cv2
l = []

# Specify the directory path containing the images
directory_path = '/home/teena/Documents/OCR_IMAGE_TEXT/cropped_image'

# Get the list of files in the directory
file_list = os.listdir(directory_path)

# Loop through each file in the directory
for file_name in file_list:
    # Construct the full path of the image file
    image_path = os.path.join(directory_path, file_name)

    # Read the image using OpenCV
    image = cv2.imread(image_path)
    st = pytesseract.image_to_string(image)
    cleaned_text = st.strip().replace('\n', ' ').replace('\x0c', '')
    print("cleaned_text",cleaned_text)
    l.append([cleaned_text])
print(l)

cleaned_text MMMM  invoice
cleaned_text SHIP TO  Kavindra Mannan 264, Abdul Rehman Mumbai, Bihar 40009
cleaned_text AMOUNT     9,999.00     1,950.00        297.00
cleaned_text 
cleaned_text ary
cleaned_text IN-001 29701/2019  2430/2019 26/04/2019
cleaned_text TERMS & CONDITIONS Payment is due within 15 days State Bank of india  Account Number: 12345678 Routing Number: 09876543210
cleaned_text BILL TO  Kavindra Mannan 27, Dif City, Gupta Delhi, Dethi 40003
cleaned_text INVOICE # INVOICE DATE P.O.#  DUE DATE
cleaned_text 
cleaned_text UNIT PRICE     9,999.00     975.00        99.00
cleaned_text 
cleaned_text FROM  Saffron Design 77 Namrata Bldg Delhi, Dethi 400077
cleaned_text DESCRIPTION     Frontend design restructure     Custom icon package        Gandhi mouse pad
cleaned_text Pays)
cleaned_text 
cleaned_text Subtotal GST 12.0%     ¥13,715.52
cleaned_text 
[['MMMM  invoice'], ['SHIP TO  Kavindra Mannan 264, Abdul Rehman Mumbai, Bihar 40009'], ['AMOUNT     9,999.00     1,950.00        

In [10]:
l

[['Bill To  Kavindra Mannan 27, Dif City, Gupta Delhi, Dethi 40003'],
 ['QTy'],
 ['Ship To  Kavindra Mannan 264, Abdul Rehman Mumbai, Bihar 40009'],
 ['Terms & Conditions  Payment is due within 1 days  State Bank of India Account Number: 12345678 Routing Number: 09876543210'],
 ['Saffron Design  77 Namrata Bldg Delhi, Dethi 400077'],
 ['Subtotal GST 12.0%  INVOICE TOTAL'],
 ['IN-001 29/01/2019 2430/2019 26/04/2019'],
 ['AMOUNT     9,999.00 1,950.00 297.00'],
 ['Invoice # Invoice Date P.O.#  Due Date'],
 ['12,246.00  1,469.52  13,715.52'],
 ['Rap)'],
 ['UNIT PRICE     9,999.00 975.00 99.00'],
 ['DESCRIPTION  Frontend design restructure Custom icon package  Gandhi mouse pad']]

In [23]:
def extract_information(data):
    bill_to = None
    ship_to = None
    terms_conditions = None
    unit_price = None
    description = None

    for item in data:
        text = item[0]

        if 'Bill' in text:
            bill_to = text.replace('Bill', '').strip()

        if 'Ship' in text:
            ship_to = text.replace('Ship To', '').strip()

        if 'Terms & Conditions' in text:
            terms_conditions = text.replace('Terms & Conditions', '').strip()

        if 'UNIT PRICE' in text:
            unit_price = text.replace('UNIT PRICE', '').strip()

        if 'DESCRIPTION' in text:
            description = text.replace('DESCRIPTION', '').strip()

    return bill_to, ship_to, terms_conditions, unit_price, description

In [24]:
# Extract the information
bill_to, ship_to, terms_conditions, unit_price, description = extract_information(l)

# Print the results
print("Bill To:", bill_to)
print("Ship To:", ship_to)
print("Terms & Conditions:", terms_conditions)
print("UNIT PRICE:", unit_price)
print("DESCRIPTION:", description)

Bill To: None
Ship To: None
Terms & Conditions: None
UNIT PRICE: 9,999.00     975.00        99.00
DESCRIPTION: Frontend design restructure     Custom icon package        Gandhi mouse pad


In [50]:
import json
file_path = 'data_rough.json'
formatted_data = []
m = 0
for sublist in l:
    formatted_data.append({'line'+str(m): sublist[0].strip()})
    m+=1

with open(file_path, 'w') as file:
    json.dump(formatted_data, file, indent=4)